AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Banking Transaction Pipeline

Globals:
  Function:
    Runtime: python3.13
    Timeout: 30
    MemorySize: 256

Parameters:

  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod
    Default: dev

  ProjectName:
    Type: String
    Default: banking-pipeline
  
  LogRetentionDays:
    Type: Number
    Default: 30

Resources:

  #########################################################
  # DynamoDB Table
  #########################################################

  BankTransactionsTable:
    Type: AWS::DynamoDB::Table

    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

    Properties:

      TableName: !Sub "${ProjectName}-${Environment}-transactions"

      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:
        - AttributeName: transaction_id
          AttributeType: S

      KeySchema:
        - AttributeName: transaction_id
          KeyType: HASH

      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false

      SSESpecification:
        SSEEnabled: true

      Tags:
        - Key: Environment
          Value: !Ref Environment

        - Key: Project
          Value: Banking Pipeline

        - Key: Owner
          Value: Kumar Nitin

  #########################################################
  # SNS Topic
  #########################################################

  TransactionNotificationTopic:
    Type: AWS::SNS::Topic

    Properties:

      TopicName: !Sub "${ProjectName}-${Environment}-alerts"

      KmsMasterKeyId: alias/aws/sns

      Tags:
        - Key: Environment
          Value: !Ref Environment

        - Key: Project
          Value: Banking Pipeline


  #########################################################
  # Dead Letter Queue
  #########################################################

  TransactionDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${ProjectName}-${Environment}-dlq.fifo"
      FifoQueue: true
      ContentBasedDeduplication: true
      SqsManagedSseEnabled: true

      Tags:
        - Key: Environment
          Value: !Ref Environment

        - Key: Project
          Value: Banking Pipeline

  #########################################################
  # SQS Queue
  #########################################################

  TransactionQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${ProjectName}-${Environment}.fifo"
      FifoQueue: true
      ContentBasedDeduplication: true
      SqsManagedSseEnabled: true

      RedrivePolicy:
        deadLetterTargetArn: !GetAtt TransactionDLQ.Arn
        maxReceiveCount: 3

      Tags:
        - Key: Environment
          Value: !Ref Environment

        - Key: Project
          Value: Banking Pipeline


#########################################################
# API Gateway
#########################################################

  TransactionApi:
    Type: AWS::Serverless::Api

    Properties:

      Name: !Sub "${ProjectName}-${Environment}-api"

      StageName: !Ref Environment

      EndpointConfiguration: REGIONAL

      TracingEnabled: true


      Cors:

        AllowMethods: "'GET,POST,OPTIONS'"

        AllowHeaders: "'Content-Type,Authorization'"

        AllowOrigin: "'*'"

      MethodSettings:

        - HttpMethod: "*"

          ResourcePath: "/*"

          MetricsEnabled: true

          LoggingLevel: INFO

          DataTraceEnabled: false

          ThrottlingBurstLimit: 100

          ThrottlingRateLimit: 50

      AccessLogSetting:
        DestinationArn: !GetAtt ApiGatewayLogGroup.Arn
        Format: '{"requestId":"$context.requestId","ip":"$context.identity.sourceIp","caller":"$context.identity.caller","user":"$context.identity.user","requestTime":"$context.requestTime","httpMethod":"$context.httpMethod","resourcePath":"$context.resourcePath","status":"$context.status","protocol":"$context.protocol","responseLength":"$context.responseLength","integrationError":"$context.integration.error"}'

      Variables:

        Environment: !Ref Environment

      Tags:

        Environment: !Ref Environment

        Project: BankingPipeline


  #########################################################
  # Validation Lambda
  #########################################################

  ValidationFunction:
    Type: AWS::Serverless::Function

    Properties:

      FunctionName: !Sub "${ProjectName}-${Environment}-validation"

      Tracing: Active

      CodeUri: src/

      Handler: lambdas.validation.app.lambda_handler

      Policies:
        - AWSLambdaBasicExecutionRole

        - AWSXRayDaemonWriteAccess

        - SQSSendMessagePolicy:
            QueueName: !GetAtt TransactionQueue.QueueName

      Environment:
        Variables:
          QUEUE_URL: !Ref TransactionQueue
          ENVIRONMENT: !Ref Environment

      Events:
        ValidateTransaction:
          Type: Api
          Properties:
            RestApiId: !Ref TransactionApi
            Path: /validate
            Method: POST


#########################################################
# Validation Lambda Log Group
#########################################################

  ValidationLogGroup:
    Type: AWS::Logs::LogGroup

    Properties:

      LogGroupName: !Sub "/aws/lambda/${ProjectName}-${Environment}-validation"

      RetentionInDays: !Ref LogRetentionDays

  #########################################################
  # Processor Lambda
  #########################################################

  ProcessorFunction:
    Type: AWS::Serverless::Function

    Properties:

      FunctionName: !Sub "${ProjectName}-${Environment}-processor"

      Tracing: Active

      CodeUri: src/

      Handler: lambdas.processor.app.lambda_handler

      Policies:

        - AWSLambdaBasicExecutionRole

        - AWSXRayDaemonWriteAccess

        - DynamoDBCrudPolicy:
            TableName: !Ref BankTransactionsTable

        - SNSPublishMessagePolicy:
            TopicName: !GetAtt TransactionNotificationTopic.TopicName

        - Statement:
            - Effect: Allow
              Action:
                - events:PutEvents
              Resource: !GetAtt TransactionEventBus.Arn
              
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: "*"

        - S3CrudPolicy:
              BucketName: !Ref TransactionArchiveBucket

      Environment:
        Variables:
          TOPIC_ARN: !Ref TransactionNotificationTopic
          TABLE_NAME: !Ref BankTransactionsTable
          EVENT_BUS_NAME: !Ref TransactionEventBus
          ARCHIVE_BUCKET: !Ref TransactionArchiveBucket
          ENVIRONMENT: !Ref Environment

      Events:

        SQSTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt TransactionQueue.Arn
            BatchSize: 1

########################################################
# Processor Lambda Log Group Retention
#######################################################

  ProcessorLogGroup:
    Type: AWS::Logs::LogGroup

    Properties:

      LogGroupName: !Sub "/aws/lambda/${ProjectName}-${Environment}-processor"

      RetentionInDays: !Ref LogRetentionDays


  #########################################################
  # Fraud Lambda
  #########################################################

  FraudFunction:
    Type: AWS::Serverless::Function

    Properties:
      FunctionName: !Sub "${ProjectName}-${Environment}-fraud"

      Tracing: Active

      CodeUri: src/

      Handler: lambdas.fraud.app.lambda_handler

      MemorySize: 256

      Timeout: 30

      Policies:
        - AWSLambdaBasicExecutionRole

        - AWSXRayDaemonWriteAccess

        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: "*"
      
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment

##################################################################
# Fraud Lamda log Group
#################################################################

  FraudLogGroup:
    Type: AWS::Logs::LogGroup

    Properties:

      LogGroupName: !Sub "/aws/lambda/${ProjectName}-${Environment}-fraud"

      RetentionInDays: !Ref LogRetentionDays

        
#########################################################
# API Lambda
#########################################################

  ApiFunction:
    Type: AWS::Serverless::Function

    Properties:

      FunctionName: !Sub "${ProjectName}-${Environment}-api"

      Tracing: Active

      CodeUri: src/

      Handler: lambdas.api.app.lambda_handler

      Runtime: python3.13

      Policies:

        - AWSLambdaBasicExecutionRole

        - AWSXRayDaemonWriteAccess

        - SQSSendMessagePolicy:
            QueueName: !GetAtt TransactionQueue.QueueName

      Environment:

        Variables:

          QUEUE_URL: !Ref TransactionQueue
          ENVIRONMENT: !Ref Environment

      Events:

        TransactionAPI:

          Type: Api

          Properties:
            
            RestApiId: !Ref TransactionApi

            Path: /transactions

            Method: POST

###############################################################
# Api Lambda Log Group
###############################################################

  ApiLogGroup:
    Type: AWS::Logs::LogGroup

    Properties:

      LogGroupName: !Sub "/aws/lambda/${ProjectName}-${Environment}-api"

      RetentionInDays: !Ref LogRetentionDays
            

  #########################################################
  # CloudWatch Alarm - Processor Lambda Errors
  #########################################################

  ProcessorLambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm

    Properties:
      AlarmName: !Sub "${ProjectName}-${Environment}-processor-errors"

      AlarmDescription: Alarm when Processor Lambda has errors

      Namespace: AWS/Lambda

      MetricName: Errors

      Dimensions:
        - Name: FunctionName
          Value: !Ref ProcessorFunction

      Statistic: Sum

      Period: 60

      EvaluationPeriods: 1

      Threshold: 1

      ComparisonOperator: GreaterThanOrEqualToThreshold

      TreatMissingData: notBreaching

      AlarmActions:
        - !Ref TransactionNotificationTopic

  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account

    Properties:
      CloudWatchRoleArn: !GetAtt ApiGatewayCloudWatchRole.Arn

  ApiGatewayCloudWatchRole:
    Type: AWS::IAM::Role

    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

#########################################################
# EventBridge Bus
#########################################################

  TransactionEventBus:
    Type: AWS::Events::EventBus
    Properties:

      Name: !Sub "${ProjectName}-${Environment}-eventbus"

      Tags:

        - Key: Environment
          Value: !Ref Environment

        - Key: Project
          Value: Banking Pipeline


####################################################
#Event rule
###################################################

  TransactionProcessedRule:
    Type: AWS::Events::Rule

    Properties:

      EventBusName: !Ref TransactionEventBus

      EventPattern:

        source:
          - bank.transaction

        detail-type:
          - TransactionProcessed

      Targets:

        - Arn: !GetAtt AuditFunction.Arn
          Id: AuditLambdaTarget

#################################################
#Event Bridge permission to invoke Lambda 
#################################################

  AuditLambdaPermission:
    Type: AWS::Lambda::Permission

    Properties:

      Action: lambda:InvokeFunction

      FunctionName: !Ref AuditFunction

      Principal: events.amazonaws.com

      SourceArn: !GetAtt TransactionProcessedRule.Arn


########################################################
#Audit lambda
########################################################

  AuditFunction:
    Type: AWS::Serverless::Function

    Properties:

      FunctionName: !Sub "${ProjectName}-${Environment}-audit"

      CodeUri: src/

      Handler: lambdas.audit.app.lambda_handler

      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSXRayDaemonWriteAccess
      
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment

##########################################################
# Audit Lambda Log Group
#########################################################

  AuditLogGroup:
    Type: AWS::Logs::LogGroup

    Properties:

      LogGroupName: !Sub "/aws/lambda/${ProjectName}-${Environment}-audit"

      RetentionInDays: !Ref LogRetentionDays

  #########################################################
  # Step Functions Workflow
  #########################################################

  TransactionWorkflow:
    Type: AWS::Serverless::StateMachine

    Properties:

      Name: !Sub "${ProjectName}-${Environment}-workflow"

      DefinitionUri: statemachine/transaction-workflow.asl.json

      DefinitionSubstitutions:

        ValidationLambdaArn: !GetAtt ValidationFunction.Arn
        FraudLambdaArn: !GetAtt FraudFunction.Arn
        ProcessorLambdaArn: !GetAtt ProcessorFunction.Arn
        FailureLambdaArn: !GetAtt FailureFunction.Arn

      Policies:

        - LambdaInvokePolicy:
            FunctionName: !Ref ValidationFunction

        - LambdaInvokePolicy:
            FunctionName: !Ref FraudFunction

        - LambdaInvokePolicy:
            FunctionName: !Ref ProcessorFunction

        - LambdaInvokePolicy:
            FunctionName: !Ref FailureFunction

  #########################################################
  # Failure Lambda
  #########################################################

  FailureFunction:
    Type: AWS::Serverless::Function

    Properties:

      FunctionName: !Sub "${ProjectName}-${Environment}-failure"

      CodeUri: src/

      Handler: lambdas.failure.app.lambda_handler

      Policies:

        - AWSLambdaBasicExecutionRole

        - SNSPublishMessagePolicy:
            TopicName: !GetAtt TransactionNotificationTopic.TopicName

      Environment:

        Variables:

          TOPIC_ARN: !Ref TransactionNotificationTopic
          ENVIRONMENT: !Ref Environment

########################################################
# Failure Lamda Log Group
#######################################################

  FailureLogGroup:
    Type: AWS::Logs::LogGroup

    Properties:

      LogGroupName: !Sub "/aws/lambda/${ProjectName}-${Environment}-failure"

      RetentionInDays: !Ref LogRetentionDays

##############################################################
#S3 Bucket
#############################################################        

  TransactionArchiveBucket:
    Type: AWS::S3::Bucket

    Properties:

      BucketName: !Sub "${ProjectName}-${Environment}-archive-${AWS::AccountId}"

      VersioningConfiguration:
        Status: Enabled

      BucketEncryption:

        ServerSideEncryptionConfiguration:

          - ServerSideEncryptionByDefault:

              SSEAlgorithm: AES256

      PublicAccessBlockConfiguration:

        BlockPublicAcls: true

        IgnorePublicAcls: true

        BlockPublicPolicy: true

        RestrictPublicBuckets: true

      Tags:

        - Key: Environment
          Value: !Ref Environment

        - Key: Project
          Value: Banking Pipeline
#########################################################
# API Gateway Access Logs
#########################################################

  ApiGatewayLogGroup:
    Type: AWS::Logs::LogGroup

    Properties:

      LogGroupName: !Sub "/aws/apigateway/${ProjectName}-${Environment}"

      RetentionInDays: !Ref LogRetentionDays


Outputs:

  ValidationApiEndpoint:
    Description: Validation API Endpoint
    Value: !Sub "https://${TransactionApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/validate"

  TransactionApiEndpoint:
    Description: Transaction API Endpoint
    Value: !Sub "https://${TransactionApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/transactions"

  QueueUrl:
    Value: !Ref TransactionQueue

  QueueArn:
    Value: !GetAtt TransactionQueue.Arn

  TopicArn:
    Value: !Ref TransactionNotificationTopic

  DynamoDBTable:
    Value: !Ref BankTransactionsTable

  ValidationLambdaArn:
    Value: !GetAtt ValidationFunction.Arn

  ProcessorLambdaArn:
    Value: !GetAtt ProcessorFunction.Arn
  
  FraudLambdaArn:
    Description: Fraud Lambda ARN
    Value: !GetAtt FraudFunction.Arn

  DLQUrl:
    Description: Dead Letter Queue URL
    Value: !Ref TransactionDLQ

  DLQArn:
    Description: Dead Letter Queue ARN
    Value: !GetAtt TransactionDLQ.Arn

  ProcessorLambdaAlarm:
    Description: CloudWatch Alarm
    Value: !Ref ProcessorLambdaErrorAlarm

  EventBusArn:
    Description: EventBridge Bus ARN
    Value: !GetAtt TransactionEventBus.Arn

  AuditLambdaArn:
    Description: Audit Lambda ARN
    Value: !GetAtt AuditFunction.Arn

  StepFunctionArn:
    Description: Step Function ARN
    Value: !Ref TransactionWorkflow