name: AWS SAM Deploy

on:
  workflow_run:
    workflows: ["AWS SAM CI"]
    types:
      - completed

jobs:

  deploy:

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      ###################################################
      # Deploy DEV
      ###################################################

      - name: Deploy DEV Stack

        if: ${{ github.event.workflow_run.head_branch == 'main' }}

        run: |
          sam deploy \
            --stack-name banking-pipeline-dev \
            --parameter-overrides Environment=dev ProjectName=banking-pipeline \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset

      ###################################################
      # Deploy PROD
      ###################################################

      - name: Deploy PROD Stack

        if: ${{ github.event.workflow_run.head_branch == 'release' }}

        run: |
          sam deploy \
            --stack-name banking-pipeline-prod \
            --parameter-overrides Environment=prod ProjectName=banking-pipeline \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset