name: AWS SAM CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Verify SAM
        run: sam --version

      - name: Build Application
        run: sam build

      - name: Validate Template
        run: sam validate