name: AWS SAM CI

on:
  pull_request:
    branches:
      - main
      - release

  push:
    branches:
      - main
      - release

jobs:

  validate-build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Verify SAM Installation
        run: sam --version

      - name: Validate SAM Template
        run: sam validate --lint

      - name: Build SAM Application
        run: sam build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sam-build
          path: .aws-sam/build